version: '3'

services:
    kibana:
        image: kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./shell/:/tmp/shell
    web:
        image: nginx
        ports:
            - "8080:80"
        links:
            - elasticsearch
            - kibana
        volumes:
            - ./shell/:/tmp/shell
